version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/postgresql/data

  odoo:
    image: odoo:18
    depends_on:
      - db
    # The command key is added to initialize the database
    command: --init base --db_user odoo --db_password "${DB_PASSWORD}" --db_host db --db_name odoo
    environment:
      # These are still useful for other Odoo operations but not for the initial connection with the command above.
      # You can safely remove HOST, USER, and PASSWORD if you use the command directive.
      HOST: db
      USER: odoo
      PASSWORD: "${DB_PASSWORD}"
      # ADMIN_PASSWORD sets the master password for the database manager page
      ADMIN_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069"
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db_data:
