version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/postgresql/data

  odoo:
    image: odoo:18
    depends_on:
      - db
    # The command now uses the correct '-d' flag for the database name
    command: --init base -d odoo --db_user odoo --db_password "${DB_PASSWORD}" --db_host db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: "${DB_PASSWORD}"
      ADMIN_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069"
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db_data:
