services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  odoo:
    # build instead of image
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${ODOO_DB_PASSWORD}
    # no bind-mount here
    ports:
      - "8069:8069"
    command: -d odoo -i base --without-demo=all
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db_data:
