version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  odoo:
    image: odoo:18
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${ODOO_DB_PASSWORD}
    volumes:
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069"
    command: -d odoo -i base
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db_data:
